// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Comment struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	User    *User  `json:"user"`
	Post    *Post  `json:"post"`
}

type Post struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Comments []*Comment `json:"comments"`
	User     *User      `json:"user"`
}

type User struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Email    string     `json:"email"`
	Profile  *string    `json:"profile"`
	Birthday string     `json:"birthday"`
	Posts    []*Post    `json:"posts"`
	Comments []*Comment `json:"comments"`
}
